name: GitHub App Commit Action
description: Makes it simple to make verified Git commits as a GitHub app
author: David Sanders

branding:
  icon: git-commit
  color: green

inputs:
  author-email:
    description: The email address to use for the commit author
    required: false
  author-name:
    description: The name to use for the commit author
    required: false
  fail-on-no-changes:
    description: Whether or not to set action failure if there are no changes to commit
    required: false
    default: true
  force:
    description: Whether to force the update or to make sure the update is a fast-forward update when updating an existing ref
    required: false
    default: false
  message:
    description: The commit message
    required: true
  owner:
    description: The owner of the GitHub repo, defaults to the owner of the repository this action is running in
    required: false
  ref:
    description: Git reference to associate the commit with (e.g. `main`). If it does not exist it will be created. Defaults to the the current checkout ref.
    required: false
  repository:
    description: The GitHub repository to commit to, defaults to the repository this action is running in
    required: false
  token:
    description: The GitHub app installation token
    required: true
  working-directory:
    description: The working directory, defaults to the current working directory
    required: false

outputs:
  message:
    description: The commit message
  ref:
    description: The associated Git reference
  ref-operation:
    description: 'Which operation was performed on the ref: `created` or `updated`. Has no value if there were no changes to commit.'
  sha:
    description: SHA for the commit

runs:
  using: node20
  main: dist/index.js
